export_csv: True
move_pdfs: False


report_month: 202207



scraped_txt_fp: C:\Users\jazz.ooi\Desktop\proj\Sharpinvest\raw_scraped_txts\
report_pdf_fp: C:\Users\jazz.ooi\Desktop\proj\Sharpinvest\monthly_report_pdfs\
output_csv_fp: C:\Users\jazz.ooi\Desktop\proj\Sharpinvest\csv_outputs\



date_keywords: ['截至', '截止日期', '報告日期']
date_keywords_1: ['資料日期']
date_keywords_2: ['月', '年', '/', '報告']

aum_keywords: ['最新帳戶規模', '帳戶規模', '月底規模', '帳戶資產規模', '帳戶月底規模', '最新規模', '帳戶型態/規模', '規模']
aum_keywords_1: ['億', '美金', 'USD', '美元', '台幣', 'TWD', 'twd', 'NT$', 'NTD', '新臺幣', '臺幣', '新台幣', '澳幣', 'AUD', 'aud', '人民幣', 'CNY', 'cny', '百萬', '佰萬', '千萬', '仟萬', '萬', '十萬', '拾萬']
aum_avoid: ['費規模']

prodname_keywords: ['帳戶', '委託', '全委代操']
prodname_avoid: ['客服專線', '經理人報告', '六個月', '(全權委託帳戶之資產撥回機制來源可能為本金)', '全權委託帳戶之資產撥回機制來源可能為本金', '投資帳戶於資產撥回前未先扣除行政管理相關費用']

manager_keywords: ['經理人', '姓名']
manager_avoid: ['成立', '簡介月', '人壽', '全委', '經理', '管費', '管理', '全權', '投信', '全球', '單位', '位淨', '波動', '大學', '機構', '預期', '顧問', '不', '一個', '投顧', '製造', '勝率', '本月', '人', '金融', '與']

bank_keywords: ['保管銀行', '保管機構']

shares_keywords: ['前五大', '前十大', '基金名稱', '受益憑證名稱', '前 5大', '前5大', 'ETF名稱', '名稱']
shares_filter_kw: ['iShares', 'ISHARES', 'IShares', 'Ishares', '基金', 'ETF', '債券', 'INVESCO', 'Invesco', '宏利', 'QQQ', 'TRUST SERIES', '百達', 'Shares', 'shares', 'SHARES', '1000', '500', '600', 'IS', 'SPDR', '%']

...